services:
  mongodb: 
    image: mongo:latest
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: scrapes
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - data-pipeline-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      retries: 5
      start_period: 30s

networks:
  data-pipeline-net:
    driver: bridge